# Generated by Django 3.2.10 on 2023-08-11 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название жанра', max_length=70, unique=True, verbose_name='Жанр')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год')),
                ('country', models.CharField(max_length=70, verbose_name='Страна')),
                ('director', models.CharField(max_length=70, verbose_name='Режиссёр')),
                ('actors', models.TextField(verbose_name='Актёры')),
                ('play', models.IntegerField(help_text='В секундах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.genre', verbose_name='Жанр')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-date'],
            },
        ),
    ]
