# Generated by Django 3.2.10 on 2023-09-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20230824_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_delete_comment', 'Возможность удалять свой комментарий'),), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
